AddressBook/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person { get; set; }
    }
}

AddressBook/Controllers/UserController.cs
using AddressBook.Models;
using AddressBook.Utils;
using AdresKayitMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AddressBook.Controllers
{
    public class UserController : Controller
    {
        AddressBookEntities db = new AddressBookEntities();
        AES256CBC aesClass = new AES256CBC();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginCancel()
        {
            Session.Abandon();
            return View("Login");
        }
        [HttpPost]
        public ActionResult Login(Users users)
        {

            string userName = aesClass.EncryptStringToBytes_Aes(users.UserName);
            string password = aesClass.EncryptStringToBytes_Aes(users.Password);
            Users u = db.Users.FirstOrDefault(x => x.Password == password && x.UserName == userName);
            if (u != null)
            {
                //byte[] bArray = Encoding.ASCII.GetBytes(u.UserName);
                //string UserName = aesClass.DecryptStringFromBytes_Aes(bArray);
                Session["Email"] = u.Email;
                Session["Id"] = u.Id;
                Session.Timeout = 10;


                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Error = "Kullanıcı Adı yada Şifre Yanlış";
                return View();
            }

        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(Users users)
        {
            Users u = db.Users.FirstOrDefault(x => x.Email == users.Email);
            if (u == null)
            {
                users.Name = aesClass.EncryptStringToBytes_Aes(users.Name);
                users.SurName = aesClass.EncryptStringToBytes_Aes(users.SurName);
                users.UserName = aesClass.EncryptStringToBytes_Aes(users.UserName);
                users.Password = aesClass.EncryptStringToBytes_Aes(users.Password);

                db.Users.Add(users);
                db.SaveChanges();
                //byte[] bArray = Encoding.ASCII.GetBytes(users.UserName);
                //string UserName = aesClass.DecryptStringFromBytes_Aes(bArray);
                Session["Email"] = users.Email;
                Session["Id"] = users.Id;
                Session.Timeout = 10;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorMail = "Bu mail adresi daha önce kayıt edilmiştir. Lütfen farklı bir tane deneyiniz.";
                return View("Register");
            }
        }
        public ActionResult UsersList()
        {
            List<Users> users = db.Users.ToList();

            foreach (Users item in users)
            {
                item.Name = aesClass.DecryptStringFromBytes_Aes(item.Name);
                item.SurName = aesClass.DecryptStringFromBytes_Aes(item.SurName);
                item.Password = aesClass.DecryptStringFromBytes_Aes(item.Password);
                item.UserName = aesClass.DecryptStringFromBytes_Aes(item.UserName);
            }
            return View(users);
        }
        [HttpPost]
        public ActionResult UsersList(List<Users> users)
        {

            return View(users);
        }
        [HttpPost]
        public ActionResult UsersListName()
        {
            List<Users> users = db.Users.ToList();
            foreach (Users item in users)
            {
                item.Name = aesClass.DecryptStringFromBytes_Aes(item.Name);
                item.SurName = aesClass.DecryptStringFromBytes_Aes(item.SurName);
                item.Password = aesClass.DecryptStringFromBytes_Aes(item.Password);
                item.UserName = aesClass.DecryptStringFromBytes_Aes(item.UserName);
            }

            return View("UsersList", users.OrderBy(x => x.Name).ToList());
        }
        [HttpPost]
        public ActionResult UsersListSurName()
        {
            List<Users> users = db.Users.ToList();

            foreach (Users item in users)
            {
                item.Name = aesClass.DecryptStringFromBytes_Aes(item.Name);
                item.SurName = aesClass.DecryptStringFromBytes_Aes(item.SurName);
                item.Password = aesClass.DecryptStringFromBytes_Aes(item.Password);
                item.UserName = aesClass.DecryptStringFromBytes_Aes(item.UserName);
            }

            return View("UsersList", users.OrderBy(x => x.SurName).ToList());

        }
    }
}

AddressBook/Views/User/Login.cshtml
@{

    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Giriş Yap</title>
    <!-- Bootstrap core CSS-->
    <link href="/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="/Content/css/sb-admin.css" rel="stylesheet">
</head>
<body class="bg-dark">
    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Giriş Yap</div>
            <div class="card-body">
                <form action="/User/Login" method="post">
                    <div class="form-group">
                        <label for="inputUserName">Kullanıcı Adı</label>
                        <input name="UserName" class="form-control" id="UserName" type="text" aria-describedby="UserName" placeholder="Kullanıcı Adınızı Giriniz">
                    </div>
                    <div class="form-group">
                        <label for="InputPassword1">Şifre</label>
                        <input name="Password" class="form-control" id="Password" type="password" placeholder="Şifrenizi Giriniz">
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox"> Şifreyi Hatırla
                            </label>
                        </div>
                    </div>
                    <input class="btn btn-primary btn-block" type="submit" value="Giriş Yap" />
                    @{
                        if (ViewBag.Error != null)
                        {
                            <label style="color:red">@ViewBag.Error</label>
                        }
                    }

                </form>
                <div class="text-center">
                    <a  class="d-block small mt-3" href="/User/Register">Yeni Kayıt Oluştur</a>
                    @*<a class="d-block small" href="forgot-password.html">Şifremi Unuttum</a>*@
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="/Content/vendor/jquery/jquery.min.js"></script>
    <script src="/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
</body>
</html>

AddressBook/Views/User/Register.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Kayıt Ol</title>
    <!-- Bootstrap core CSS-->
    <link href="/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="/Content/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="/Content/css/sb-admin.css" rel="stylesheet">
</head>
<body class="bg-dark">
    <div class="container">
        <div class="card card-register mx-auto mt-5">
            <div class="card-header">Yeni Kayıt</div>
            <div class="card-body">
                <form action="/User/Register" method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Mail</label>
                        <input name="Email" class="form-control" id="exampleInputEmail1" type="email" aria-describedby="emailHelp" placeholder="Mail Adresinizi Giriniz">
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="Name">Adı</label>
                                <input name="Name" class="form-control" id="Name" type="text" aria-describedby="nameHelp" placeholder="Adını Giriniz">
                            </div>
                            <div class="col-md-6">
                                <label for="SurName">Soy Adı</label>
                                <input name="SurName" class="form-control" id="SurName" type="text" placeholder="Soy Adınızı Giriniz">
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-6">
                                <label for="exampleInputName">Kullanıcı Adı</label>
                                <input name="UserName" class="form-control" id="exampleInputName" type="text" aria-describedby="nameHelp" placeholder="Kullanıcı Adını Giriniz">
                            </div>
                            <div class="col-md-6">
                                <label for="exampleInputPassword1">Şifre</label>
                                <input name="Password" class="form-control" id="exampleInputPassword1" type="password" placeholder="Şifrenizi Giriniz">
                            </div>

                        </div>
                    </div>

                    <input class="btn btn-primary btn-block" type="submit" value="Kayıt Ol" />
                </form>
                <div class="text-center">

                    <a class="d-block small mt-3" href="/User/Login">Giriş Yap</a>
                    @if (ViewBag.ErrorMail != null)
                    {
                        <label style="color:red">@ViewBag.ErrorMail</label>
                    }

                    @*<a class="d-block small" href="forgot-password.html">Şifrenizi mi Unuttunuz?</a>*@
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="/Content/vendor/jquery/jquery.min.js"></script>
    <script src="/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
</body>
</html>

AddressBook/Views/User/UsersList.cshtml
@{
    ViewBag.Title = "Kullanıcılar";
}

@using AddressBook.Models
@model List<Users>
<!DOCTYPE html>

<html>
<body>
    <table>

        <tr>
            <td>
                <div>
                    @using (Html.BeginForm("UsersListName", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        <input type="submit" value="Ad'a Göre Sıralama" class="btn btn-secondary " />

                    }

                </div>
            </td>
            <td>
                <div>
                    @using (Html.BeginForm("UsersListSurname", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        <input type="submit" value="Soyad'a Göre Sıralama" class="btn btn-secondary" />

                    }

                </div>
            </td>
    </table>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Kullanıcıların Listesi
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Adı</th>
                    <th>Soyadı</th>
                    <th>Kullanıcı Adı</th>
                    <th>Email</th>
                    <th>Password</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Adı</th>
                    <th>Soyadı</th>
                    <th>Kullanıcı Adı</th>
                    <th>Email</th>
                    <th>Password</th>
                </tr>
            </tfoot>
            <tbody>
                @foreach (Users item in Model)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.SurName</td>
                        <td>@item.UserName</td>
                        <td>@item.Email</td>
                        <td>@item.Password</td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="card-footer small text-muted">Güncellenme Tarihi: @DateTime.Now</div>
    </div>

</body>
</html>